version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2
  parameter-store:
    ROLE_ARN: /codebuild/pttp-ci-infrastructure-core-pipeline/development/assume_role # tests hardcoded to only run in development
    SHARED_SERVICES_ACCOUNT_ID: /codebuild/staff_device_shared_services_account_id

phases:
  install:
    commands:
      - git clone https://github.com/ministryofjustice/network-access-control-integration-tests.git
      - cd network-access-control-integration-tests && make clone-admin clone-server test
