version: 0.2
env:
  variables:
    AWS_REGION: eu-west-2
  parameter-store:
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  install:
    commands:
      - git clone -b update-bundler https://github.com/ministryofjustice/network-access-control-integration-tests.git
      - cd network-access-control-integration-tests && make clone-admin clone-server test
