version: 0.2

env:
  variables:
    DB_PORT: 3306
  parameter-store:
    REGISTRY_URL: "/moj-network-access-control/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    TERRAFORM_OUTPUTS: "/moj-network-access-control/terraform/$ENV/outputs"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"

phases:
  build:
    commands:
      - make authenticate-docker
      - make publish