version: "3.4"

services:
  server:
    build:
      context: .
    expose:
      - "1812/udp"
      - "1813/udp"
    environment:
      DB_HOST: db
      DB_USER: radius
      DB_PASS: radius
      DB_NAME: radius
      LOCAL_DEVELOPMENT: "true"
    depends_on: 
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  client:
    build:
      context: .
    expose:
      - "1812/udp"
      - "1813/udp"
    environment:
      DB_HOST: db
      DB_USER: radius
      DB_PASS: radius
      DB_NAME: radius
      LOCAL_DEVELOPMENT: "true"
    depends_on: 
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: radius
      MYSQL_PASSWORD: radius
      MYSQL_DATABASE: radius
    ports:
    - 3306:3306
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
