version: "3.4"

services:
  server:
    build:
      context: .
      args: 
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    expose:
      - "1812/udp"
      - "1813/udp"
      - "2083/tcp"
    volumes:
      - './test:/test'
    environment:
      DB_HOST: db
      DB_USER: radius
      DB_PASS: radius
      DB_NAME: radius
      OCSP_URL: "127.0.0.1:9999"
      LOCAL_DEVELOPMENT: "true"
      CONTAINER_NAME: "server"
      ENABLE_CRL: "yes"
    depends_on: 
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  client:
    build:
      context: .
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    volumes:
      - './test:/test'
    expose:
      - "1812/udp"
      - "1813/udp"
      - "2083/tcp"
    environment:
      DB_HOST: db
      DB_USER: radius
      DB_PASS: radius
      DB_NAME: radius
      OCSP_URL: "127.0.0.1:9999"
      LOCAL_DEVELOPMENT: "true"
      CONTAINER_NAME: "test-client"
      ENABLE_CRL: "yes"
    depends_on: 
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  certgenerator:
    build:
      context: ./test/generate_certs
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    command: sh -c "bootstrap.sh && sleep infinity"

  radsecproxy:
    build:
      context: ./test/radsecproxy
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    volumes:
      - './test/certs:/certs'
    expose:
      - "1812/udp"
      - "1813/udp"
      - "2083/tcp"
      - "18120/udp"
    environment:
      DB_HOST: db
      DB_USER: radius
      DB_PASS: radius
      DB_NAME: radius
      OCSP_URL: "127.0.0.1:9999"
      LOCAL_DEVELOPMENT: "true"
      CONTAINER_NAME: "radsecproxy"
    depends_on: 
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  db:
    image: "${SHARED_SERVICES_ACCOUNT_ID}.dkr.ecr.eu-west-2.amazonaws.com/admin-mysql:mysql-5-7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: radius
      MYSQL_PASSWORD: radius
      MYSQL_DATABASE: radius
    ports:
    - 3306:3306
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
